### ISSUE TITLE
Add a license 

### ISSUE THREAD

**Issue by AdrianVazquezMejia** [gamesMum/Leukemia-Diagnostics#2]
Hi, I think is a amazing approach.  It could be a good collaborative project. In order clear the rules using this work, it would be a good idea add a  open source License.

[This](https://choosealicense.com) site has some options. I recommend the MIT license.

**Comment by AdrianVazquezMejia** [comment]
I saw you have it, in a separate archive, but it's a good idea put it in the readme too

**Comment by rasha-salim** [comment]
Thanks a lot! I merged the request. This is the first time for me in dealing with licencing so really appreciate it.
